version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./uploads:/var/www/html/uploads
      - ./php:/var/www/html
    depends_on:
      - php
    restart: always

  php:
    build: ./php
    command: bash -c "/usr/local/bin/wait-for-it.sh db:3306 -- /usr/local/sbin/php-fpm -F"
    volumes:
      - ./php:/var/www/html
      - ./uploads:/var/www/html/uploads
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: velo
      MYSQL_USER: velo
      MYSQL_PASSWORD: velo
    ports:
      - "3306:3306"
    volumes:
      - ./db/products.sql:/docker-entrypoint-initdb.d/products.sql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: always 