DROP TABLE IF EXISTS products;

CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price VARCHAR(32),
    image VARCHAR(255),
    image2 VARCHAR(255),
    image3 VARCHAR(255),
    image4 VARCHAR(255)
);

INSERT INTO products (name, description, price, image, image2, image3, image4) VALUES
('Cervélo CALEDONIA-5 - Rival eTap AXS - Carbon Rennrad - 2024 five black', 'Dein Bike für klassische Ausfahrten. Das Caledonia-5 ist das Bike, zu dem Cervélo immer wieder greifen, wenn sie wissen, dass der Computer weit über die dreistellige km Marke anzeigen wird. Lange Fahrten haben immer etwas glatten Asphalt, Schlaglöcher auf Nebenstraßen, eine knackige Abkürzung zwischen offiziellen Wegen und vielleicht sogar einen eigenen lokalen Strade Bianche-Sektor. Also haben Cervélo ein Rad gebaut, das alle diese Anforderungen erfüllt und zusätzlich mit Schutzblechen ausgestattet werden kann, falls sich diese komischen Wolken nach 130 km in einen Regenguss verwandeln sollten. Der Rahmen, die Gabel, der Lenker und die dazugehörigen Komponenten von Cervélo sind so konzipiert, dass die Brems- und Schaltzüge (mechanisch, elektrisch und hydraulisch) vor dem Wind geschützt sind, um die Aerodynamik zu verbessern, ohne dass die Benutzerfreundlichkeit oder die Leistung beeinträchtigt wird. Eigenschaften von Cervélo CALEDONIA-5: Leichter Carbon Rahmen und Gabel Aerodynamische Form Integrierte Zubehörhalterungen Abschraubbare Umwerferbefestigung 34 mm Reifenfreiheit Interne Zugführung', '4.699,00', 'uploads/Cervélo CALEDONIA-5.png', 'uploads/Cervélo CALEDONIA-5/Cervélo_1.jpg', 'uploads/Cervélo CALEDONIA-5/Cervélo_2.jpg', 'uploads/Cervélo CALEDONIA-5/Cervélo_3.jpg'),
('Cinelli HOBOOTLEG GEO - Shimano Tiagra Gravel Bike - 2023 - orange', 'Reisen und erkunden! Das Cinelli Hobootleg GEO ist das ausgereifteste und abenteuerlustigste Bike aller Zeiten. Drei Jahre Tests mit den erfahrensten und anspruchsvollsten Off-Road-Bikern führten zu einer überarbeiteten Geometrie und lieferten die notwendigen Eigenschaften, um dieses Fahrrad zu einem Pionier im sich schnell entwickelnden Sektor des selbstversorgten Reisens zu machen. Besondere Merkmale des Cinelli Hobootleg GEO: Rahmen aus Columbus-Stahl, Columbus Futura Adventure Carbongabel, Shimano Tiagra / Deore 2x10 Antrieb, WTB Ranger Reifen, diverse Zubehörbefestigungen.', '2.299,99', 'uploads/Cinelli HOBOOTLEG GEO.png', 'uploads/Cinelli HOBOOTLEG GEO/Cinelli HOBOOTLEG GEO_1.jpg', 'uploads/Cinelli HOBOOTLEG GEO/Cinelli HOBOOTLEG GEO_2.jpg', 'uploads/Cinelli HOBOOTLEG GEO/Cinelli HOBOOTLEG GEO_3.jpg'),
('FOCUS ATLAS 8.9 - Carbon Gravel Bike - 2023 - Gold Brown', 'Kennt keine Grenzen. Die FOCUS ATLAS 8 Serie bietet bis zu 45 mm Reifenfreiheit und alle Befestigungsmöglichkeiten für Bikepacking-Abenteuer. Ob schlechtes Wetter, schwieriges Gelände, steile Anstiege oder weite Distanzen – das schnelle und komfortable Gravelbike bietet volle Kontrolle und maximale Variabilität. Der breite Lenker mit Flare und Scheibenbremsen sorgen für hohe Sicherheit und Komfort bei dem leichten und agilen Carbon-Bike mit integrierter C.I.S. Kabelführung. Das Gravelbike wird mit einer Oberrohrtasche (Top Tube Bag) geliefert, die schnell und einfach zugänglich ist. Was auch immer Sie vorhaben, der ATLAS bringt Sie hin – sogar ans Ende der Welt. Hauptmerkmale des FOCUS ATLAS 8.9 Carbon: Leichter Carbonrahmen und -gabel mit vollständig integrierter C.I.S. Kabelführung durch den Vorbau sowie eine Oberrohrtasche. SRAM Rival ETAP AXS XPLR: kabellose elektronische Schaltung mit gravelspezifischer 1x12 Übersetzung (40/10–44). Leichter und super stabiler High-End Gravel-Laufradsatz: DT Swiss GR1600 Road Boost Laufräder mit doppelt gedichteten Lagern.', '3.399,00', 'uploads/FOCUS ATLAS 8-9.png', 'uploads/FOCUS ATLAS 8-9/FOCUS ATLAS 8-9_1.jpg', 'uploads/FOCUS ATLAS 8-9/FOCUS ATLAS 8-9_2.jpg', 'uploads/FOCUS ATLAS 8-9/FOCUS ATLAS 8-9_3.jpg'),
('Cinelli ZYDECO - Shimano GRX Gravel Bike - 2023 - muddy dry', 'Cinelli Zydeco bietet das Beste für Gravel und ist eine einzigartige Kombination aus Rennrad, Reiserad und Gravelbike. Sagen Sie Zydeco und sagen Sie Gravel. Und Zydeco hält seine Versprechen, entwickelt sich ständig weiter und bleibt seiner Seele treu. In diesem treuen Streben nach Neuem verbindet sich die verbesserte Bremseffizienz der Steckachse и des hydraulischen Bremssystems mit der gravelspezifischen Shimano GRX-Gruppe, die mit ihrem Shadow RD+ System und dem ergonomischsten Hebelmechanismus mit gekrümmter Form und rutschfester Beschichtung eine erhöhte Zuverlässigkeit in Bezug auf die Getriebeeffizienz für perfekte Offroad-Kontrolle bietet. Hauptmerkmale des Cinelli Zydeco Gravelbikes: leichter Aluminiumrahmen, großer Radstand ermöglicht die Montage von Schutzblechen, 2 zusätzliche Ösen am Oberrohr ermöglichen die optimale und sichere Befestigung von Taschen, Columbus Futura Gravel Carbon-Monocoque-Gabel mit interner Kabelführung und Flat Mount Disc Aufnahme, Reifenbreite bis 40 mm.', '2.099,00', 'uploads/Cinelli ZYDECO.png', 'uploads/Cinelli ZYDECO/Cinelli2_1.jpg', 'uploads/Cinelli ZYDECO/Cinelli2_2.jpg', 'uploads/Cinelli ZYDECO/Cinelli2_3.jpg'),
('Cinelli ZYDECO LALA - Gravel Bike - 2023 - mr blue sky', 'Für Abenteuer geschaffen! Das Cinelli Zydeco LaLa ist ein Mitglied der Zydeco Gravelbike-Familie. Es ist aus konifizierten Columbus Zonal Aluminiumrohren gefertigt und mit bewährten Komponenten ausgestattet. Hauptmerkmale des Cinelli Zydeco LaLa: Columbus Aluminiumrahmen, Columbus Futura Gravel Carbongabel, geeignet für die Montage von Schutzblechen und Gepäckträger, Shimano Sora 2x9 Antrieb, Tektro mechanische Scheibenbremsen.', '1.489,00', 'uploads/Cinelli ZYDECO LALA.png', 'uploads/Cinelli ZYDECO LALA/Cinelli3_1.jpg', 'uploads/Cinelli ZYDECO LALA/Cinelli3_2.jpg', 'uploads/Cinelli ZYDECO LALA/Cinelli3_3.jpg'),
('Cinelli HOBOOTLEG - Adventure Bike - 2023 - red right hand', 'Das Flaggschiff der Abenteuerfahrräder! Seit seiner ursprünglichen Konzeption und Verfeinerung in zwei aufeinanderfolgenden Ausgaben der legendären Tour d''Afrique in den Jahren 2012 und 2013 hat der Hobo Bootleg den Guinness-Weltrekord für eine Weltumrundung mit dem Fahrrad gebrochen, alle sieben höchsten Bergpässe der Welt bezwungen und über eine Million Kilometer Abenteuerfahrten zurückgelegt. Hauptmerkmale des Cinelli HOBOOTLEG: robuster Rahmen aus CrMo Columbus, Shimano 3x9 Antrieb, Tektro Felgenbremsen, ergonomischer Lenkerstopper, interne Zugführung am Oberrohr, WTB Riddler Reifen, vorderer und hinterer Gepäckträger, vordere und hintere Schutzbleche.', '1.549,99', 'uploads/Cinelli HOBOOTLEG.png', 'uploads/Cinelli HOBOOTLEG/Cinelli4_1.jpg', 'uploads/Cinelli HOBOOTLEG/Cinelli4_2.jpg', 'uploads/Cinelli HOBOOTLEG/Cinelli4_3.jpg'),
('CUBE NUROAD C:62 SLT - Carbon Gravel Bike - 2023 - liquidred / red', 'Das nächste Abenteuer wartet schon! SLT im Produktnamen muss man sich verdienen – nur die besten CUBE Bikes tragen dieses Gütesiegel. Im Fall des Nuroad C:62 SLT gilt das für einen außergewöhnlich schnellen, leichten und vielseitigen Allrounder mit Vollcarbonrahmen und -gabel in Kombination mit Hightech-Komponenten. Dazu gehört eine 12-fach XX1 Eagle AXS Schaltung von SRAM für butterweiche Gangwechsel mit breitem Übersetzungsbereich. Die Offroad-Carbonlaufräder von Newmen Advanced mit Schwalbe Reifen haben ihre Qualität bereits im Mountainbike-Einsatz unter Beweis gestellt, was bedeutet: Sie sind extrem griffig und robust. Hinzu kommen kraftvolle hydraulische Scheibenbremsen, die in jeder Situation und bei allen Bedingungen volle Kontrolle und Sicherheit bieten. Voll beladen für die lange Tour oder clean und pur für schnelle Feierabendrunden – die Wahl liegt bei Ihnen! Features des CUBE NUROAD C:62 SLT: C:62 Advanced Twin Mold Carbonrahmen, interne Kabelführung, Flat Mount Disc Aufnahme, Befestigungsmöglichkeiten für Schutzbleche, Gepäckträger und Seitenständer, 45 mm Reifenfreiheit (ohne Schutzbleche), Vollcarbongabel.', '3.969,00', 'uploads/CUBE NUROAD C-62 SLT.png', 'uploads/CUBE NUROAD C-62 SLT/CUBE3_1.jpg', 'uploads/CUBE NUROAD C-62 SLT/CUBE3_2.jpg', 'uploads/CUBE NUROAD C-62 SLT/CUBE3_3.jpg'),
('FOCUS ATLAS 6.8 - Gravel Bike - 2024 - Heritageblue / Stoneblue glossy', 'ATLAS 6.8: Schnelles Gravelbike für Gravel-Abenteuer und Bikepacking. Kennt keine Grenzen: Der ATLAS bietet bis zu 47 mm Reifenfreiheit und alle Befestigungsmöglichkeiten für Bikepacking. Ob schlechtes Wetter, anspruchsvolles Gelände, steile Anstiege oder weite Distanzen – das schnelle und komfortable Gravelbike bietet volle Kontrolle und maximale Variabilität. Ein breiter Lenker mit Flare und Scheibenbremsen sorgen für hohe Sicherheit und Komfort bei dem leichten und robusten Aluminiumrad mit Carbongabel. Was auch immer Sie vorhaben, der ATLAS bringt Sie hin – selbst ans Ende der Welt. Ein aufgeräumtes Cockpit mit Kabelführung durch den Steuersatz sorgt zudem dafür, dass sich eine Lenkertasche einfach anbringen lässt. Dank der Befestigungspunkte an der Gabel können Gepäckträger mit 3 kg Traglast pro Seite montiert werden. Und mit jedem ATLAS 6.8 wird eine Oberrohrtasche geliefert, in der alles Wichtige Platz findet. Features des FOCUS ATLAS 6.8 Gravelbikes: leichter, robuster Aluminiumrahmen und Carbongabel mit integrierter C.I.S. Kabelführung sowie Befestigungsmöglichkeiten für Schutzbleche, Gepäckträger und Seitenständer. Shimano GRX600 2x11 Gruppe für zuverlässiges Schalten und sicheres Bremsen auch in anspruchsvollem Gelände. Maximale Stabilität und hohe Qualität: DT Swiss Road Boost System Laufräder.', '2.299,00', 'uploads/FOCUS ATLAS 6-8.png', 'uploads/FOCUS ATLAS 6-8/FOCUS4_1.jpg', 'uploads/FOCUS ATLAS 6-8/FOCUS4_2.jpg', 'uploads/FOCUS ATLAS 6-8/FOCUS4_3.jpg'); 